name: Development build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Setup Cache 
      uses: actions/cache@v2.1.6
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Checkout GitHub Actions
      uses: actions/checkout@v2.3.4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: '2.2'
        
    - name: Restore dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: dotnet restore BMG.sln
  
    - name: Build
      run: dotnet build BMG.sln --configuration Release --no-restore -o output
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Build-Artifact
        path: ./output
        
