name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Setup Cache 
      uses: actions/cache@v2.1.6
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
          
    - name: Setup Zip
      uses: montudor/action-zip@v1.0.0

    - name: Checkout GitHub Actions
      uses: actions/checkout@v2.3.4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: '2.2'
        
    - name: Restore dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: dotnet restore BMG.sln
      
    - name: Build
      run: dotnet build BMG.sln --configuration Release --no-restore
      
    - name: Publish application [Windows]
      run: dotnet publish BMG.sln -c Release --self-contained --no-restore -r win-x64 -f netcoreapp2.2 -o ./output/win64
      
    - name: Zip application [Windows]
      run: zip -qq -r ./win.zip ./output/win64/
      
    - name: Upload Artifact [Windows]
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Win-Artifact
        path: ./win.zip
